# This is a basic workflow to help you get started with Actions

name: My Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter Version'
        required: true
        default: 'default value'
      traffic_color:
        description: 'Enter colour'
        required: true
        default: 'green'
        
        
jobs:
   build:
     
     runs-on: ubuntu-latest
     
     steps:
     - name: checkout
       uses: rohmanngmbh/action-checkout-repo@v1.3.4
       with:
         repository: srikarchikku/testjenkins
     - name: Print Input Parameter
       run: echo "'${{inputs.release_version}}'"
            echo "'${{secrets.JENKINS_USERNAME}}'"
     - name: Trigger jenkins 
       run: |
        curl -X POST \
          -H "Content-Type: application/json" \ 
          -H "Authorization: Basic cGlubmEuc3Jpa2FyMUBmcmVzaHdvcmtzLmNvbToxMTY5MDMxNDA1OWI2ZWE2ZWM1YTI1Mzk0M2RhODU5NzYx" \
          -d '{
            "parameter": [
              {"name": "RELEASE_NAME", "value": "FCH22.01.3"}
            ]
          }' \
          https://freshchat-staging.runwayci.com/job/Dummy_job/buildWithParameters 
  
  
      
