# This is a basic workflow to help you get started with Actions

name: Create tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_tag:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        run: git checkout master
      - name: Create tag
        uses: simpleactions/create-tag@v1.0.0
        with:
           github_token: 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
           tag: FCH22.02.1
           message: Creating release tag
      
