# This is a basic workflow to help you get started with Actions

name: My Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter Version'
        required: true
        default: 'default value'
      traffic_color:
        description: 'Enter colour'
        required: true
        default: 'green'
        
        
jobs:
   build:
     
     runs-on: ubuntu-latest
     
     steps:
     - name: checkout
       uses: rohmanngmbh/action-checkout-repo@v1.3.4
       with:
         repository: srikarchikku/testjenkins
     - name: Print Input Parameter
       run: echo "'${{inputs.release_version}}'"
            echo "'${{secrets.JENKINS_USERNAME}}'"
     - name: Trigger jenkins 
       uses: appleboy/jenkins-action@master
       with:
        url: "http://localhost:8080.com"
        user: "pinnasrikar"
        token: ${{ secrets.JENKINS_API_TOKEN }}
        job: "Check_Job"
   
   
  
  
      
