# This is a basic workflow to help you get started with Actions

name: My Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter Version'
        required: true
        default: 'default value'
      traffic_color:
        description: 'Enter colour'
        required: true
        default: 'green'
        
        
jobs:
   build:
     
     runs-on: ubuntu-latest
     
     steps:
     - name: checkout
       uses: rohmanngmbh/action-checkout-repo@v1.3.4
       with:
         repository: srikarchikku/testjenkins
     - name: Print Input Parameter
       run: echo "'${{inputs.release_version}}'"
     - name: Trigger jenkins 
       uses: peter-evans/http-request@v2.2.1
       with:
        url: 'http://localhost:8080/job/Check_Job/buildWithParameters'
        method: 'POST'
        auth-type: 'basic'
        username: ${{ secrets.JENKINS_USERNAME }}
        password: ${{ secrets.JENKINS_PASSWORD }}
        body: |
          RELEASE_NAME= ${{inputs.release_version}}
   
   
  
  
      
