# This is a basic workflow to help you get started with Actions

name: My Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter Version'
        required: true
        default: 'default value'
      traffic_color:
        description: 'Enter colour'
        required: true
        default: 'green'
        
        
jobs:
   build:
     
     runs-on: ubuntu-latest
     
     steps:
     - name: checkout
       uses: rohmanngmbh/action-checkout-repo@v1.3.4
       with:
         repository: srikarchikku/testjenkins
     - name: Print Input Parameter
       run: echo "'${{inputs.release_version}}'"
     - name: Trigger jenkins 
       uses: jabbukka/jenkins-trigger@main
       with:
        url: "https://freshchat-staging.runwayci.com"
        job_name: "FCH-release-version-creation"
        user_name: ${{ secrets.FRESHCHAT_JENKINS_USERNAME }}
        api_token: ${{ secrets.FRESHCHAT_JENKINS_TOKEN }}
        parameter: |
          { "RELEASE_VERSION": "${{inputs.release_version}}" }
        headers: |
          {"Accept": "application/json"}
   
   
  
  
      
