# This is a basic workflow to help you get started with Actions

name: My Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter Version'
        required: true
        default: 'default value'
      traffic_color:
        description: 'Enter colour'
        required: true
        default: 'green'
        
        
jobs:
   build:
     
     runs-on: ubuntu-latest
     
     steps:
     - name: checkout
       uses: rohmanngmbh/action-checkout-repo@v1.3.4
       with:
         repository: srikarchikku/testjenkins
     - name: Print Input Parameter
       run: echo "'${{inputs.release_version}}'"
     - name: Trigger jenkins 
       uses: toptal/jenkins-job-trigger-action@master
       with:
        jenkins_url: "http://localhost:8080/"
        jenkins_user: ${{ secrets.JENKINS_USERNAME }}
        jenkins_token: ${{ secrets.JENKINS_API_TOKEN }}
        job_name: "Check_Job"
        job_params: |
          { "RELEASE_NAME": "FCH22.10.22" }
        async: true
   
   
  
  
      
