# This is a basic workflow to help you get started with Actions

name: My Workflow

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: 'Enter a value for my_input'
        required: true
        default: 'default value'
       
      
