# This is a basic workflow to help you get started with Actions

name: My Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter Version'
        required: true
        default: 'default value'
      traffic_color:
        description: 'Enter colour'
        required: true
        default: 'green'
        
        
jobs:
   build:
     
     runs-on: ubuntu-latest
     
     steps:
     - name: checkout
       uses: rohmanngmbh/action-checkout-repo@v1.3.4
       with:
         repository: srikarchikku/testjenkins
     - name: Print Input Parameter
       run: echo "'${{inputs.release_version}}'"
     - name: Trigger jenkins 
       uses: shihyuho/go-jenkins-trigger@v1
       with:
        jenkins-url: 'https://freshchat-staging.runwayci.com'
        jenkins-user: ${{ secrets.FRESHCHAT_JENKINS_USERNAME }}
        jenkins-pat: ${{ secrets.FRESHCHAT_JENKINS_TOKEN }}
        job: 'FCH-release-version-creation'
        params: RELEASE_VERSION=${{ inputs.release_version }}
   
   
  
  
      
