# This is a basic workflow to help you get started with Actions

name: My Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter Version'
        required: true
        default: 'default value'
      traffic_color:
        description: 'Enter colour'
        required: true
        default: 'green'
        
        
jobs:
   build:
     
     runs-on: ubuntu-latest
     
     steps:
     - name: checkout
       uses: rohmanngmbh/action-checkout-repo@v1.3.4
       with:
         repository: srikarchikku/testjenkins
     - name: Print Input Parameter
       run: echo "'${{inputs.release_version}}'"
            echo "'${{secrets.JENKINS_USERNAME}}'"
     - name: Trigger jenkins 
       run: |
        curl -X POST \
          -u ${{secrets.JENKINS_USERNAME}}:${{secrets.JENKINS_API_TOKEN}} \ # Replace with your Jenkins username and API token
          -H "Content-Type: application/json" \
          -d '{
            "parameter": [
              {"RELEASE_NAME": "FCH22.05.1"}
            ]
          }' \
          http://localhost:8080/job/Check_Job/buildWithParameters 
  
  
      
